dist: trusty
language: java
jdk:
  - openjdk11

jobs:
  include:
    - stage: gradle build
      script:
        - ./gradlew build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t trusted-anchor-server .
        - docker images
        - docker tag trusted-anchor-server $DOCKER_USERNAME/trusted-anchor-server
        - docker push $DOCKER_USERNAME/trusted-anchor-server
